### ISSUE TITLE
[1.21] Paxi prevents any Resource Pack from modifying modded GUIs 

### ISSUE THREAD

**Issue by muon-rw** [yungnickyoung/Packie#30]
- Install a mod with a GUI texture in its own namespace
- Add a resource pack replacing that texture 
- Install Paxi
The resource from the pack will not be loaded. 
Vanilla resource replacements in the minecraft namespace work as intended. 
Modded Non-GUI element replacements also work as intended. 

There doesn't seem to be any relevant information in it, but [here](https://mclo.gs/oStnDUL) is the log. 

Reproduction notes: 
Minecraft 1.21
Fabric Loader 0.16.0 
Fabric API 0.102.0+1.21
Paxi 5.0.0
I used the vanilla resourcepacks folder to reproduce this bug, I did not attempt loading the resource pack through Paxi.

**Comment by LPFan12** [comment]
The mod seems to break custom namespace support as a whole. I have the same issue with language files, "minecraft" as the affected namespace works fine, stuff like "controlify" or "jade" doesn't...which is bad if one wants to replace already defined strings in mods rather than just adding missing ones. The latter is possible through the "minecraft" namespace, but the former is not.

**Comment by yungnickyoung** [comment]
To clarify, this only occurs when loading resource packs through the vanilla `resourcepacks` directory, and not with Paxi, right? I can confirm that the Visual Traveler's Titles resourcepack doesn't seem to apply when using the vanilla directory, but it does function properly when loaded through Paxi.

**Comment by yungnickyoung** [comment]
This should be fixed in v5.1.2. Please lmk if the problem persists!
